from __future__ import annotations

from typing import Any, Callable

from utils import ApiError, AuthContext

from .admin import (
    copy_template_data,
    logs_query,
    my_permissions_get,
    permissions_list,
    permissions_upsert,
    roles_list,
    roles_upsert,
    settings_get,
    settings_upsert,
    template_list,
    template_upsert,
    users_list,
    users_upsert,
)
from .auth_actions import employee_login, get_me, login_exchange, session_validate
from .candidates import (
    candidate_add,
    candidate_bulk_add,
    candidate_pii_set,
    file_upload_cv,
    hold_revert,
    owner_candidates_list,
    owner_decide,
    owner_final_decide,
    reject_revert,
    rejection_log_list,
    shortlist_decide,
    shortlist_hold_revert,
)
from .jobposting import jobpost_complete, jobpost_init, jobpost_mark_portal, jobpost_set_portals, jobpost_upload_screenshot
from .pipeline import (
    admin_excel_marks_submit,
    auto_reject_final_noshow,
    auto_reject_inperson_low,
    auto_reject_notpick,
    auto_reschedule_no_show,
    docs_complete,
    docs_upload,
    ea_tech_marks_submit,
    employee_create_from_candidate,
    employee_get,
    final_interview_list,
    final_send_owner,
    hold_expiry_cron,
    hr_final_hold_list,
    hr_hold_schedule,
    hr_walkin_schedule,
    inperson_marks_save,
    inperson_pipeline_list,
    joining_list,
    joining_set_date,
    mark_join,
    passfail_evaluate,
    precall_list,
    precall_update,
    preinterview_marks_save,
    preinterview_status,
    probation_complete,
    probation_decide,
    probation_list,
    probation_set,
    requirement_auto_close,
    role_change,
    tech_pending_list,
    tech_select,
    test_fail_decide,
    test_link_create,
    test_questions_get,
    test_result_get,
    test_submit_public,
    test_token_validate,
    walkin_schedule,
)
from .requirements import (
    hr_requirements_list,
    requirement_approve,
    requirement_clarification,
    requirement_create,
    requirement_get,
    requirement_list_by_role,
    requirement_resubmit,
    requirement_submit,
    requirement_update,
)
from .training import (
    training_assign,
    training_dashboard,
    training_close,
    training_list,
    training_mark_complete,
    training_master_list,
    training_master_upsert,
    training_status_update,
    training_summary,
)
from .dynamic_tests import (
    candidate_required_tests_set,
    candidate_test_assign,
    candidate_test_review,
    candidate_test_submit,
    candidate_tests_get,
    test_master_get,
    test_master_upsert,
    tests_queue_list,
)
from .fail_candidates import fail_candidates_list
from .metrics_actions import sla_config_get, sla_config_upsert, step_metrics_query


Handler = Callable[[dict[str, Any], AuthContext | None, Any, Any], Any]


ACTION_HANDLERS: dict[str, Handler] = {
    "LOGIN_EXCHANGE": login_exchange,
    "EMPLOYEE_LOGIN": employee_login,
    "SESSION_VALIDATE": session_validate,
    "GET_ME": get_me,
    "USERS_LIST": users_list,
    "USERS_UPSERT": users_upsert,
    "ROLES_LIST": roles_list,
    "ROLES_UPSERT": roles_upsert,
    "PERMISSIONS_LIST": permissions_list,
    "PERMISSIONS_UPSERT": permissions_upsert,
    "MY_PERMISSIONS_GET": my_permissions_get,
    "TEMPLATE_LIST": template_list,
    "TEMPLATE_UPSERT": template_upsert,
    "SETTINGS_GET": settings_get,
    "SETTINGS_UPSERT": settings_upsert,
    "COPY_TEMPLATE_DATA": copy_template_data,
    "LOGS_QUERY": logs_query,
    "REQUIREMENT_CREATE": requirement_create,
    "REQUIREMENT_UPDATE": requirement_update,
    "REQUIREMENT_SUBMIT": requirement_submit,
    "REQUIREMENT_RESUBMIT": requirement_resubmit,
    "REQUIREMENT_GET": requirement_get,
    "REQUIREMENT_LIST_BY_ROLE": requirement_list_by_role,
    "HR_REQUIREMENTS_LIST": hr_requirements_list,
    "REQUIREMENT_APPROVE": requirement_approve,
    "REQUIREMENT_CLARIFICATION": requirement_clarification,
    "JOBPOST_INIT": jobpost_init,
    "JOBPOST_SET_PORTALS": jobpost_set_portals,
    "JOBPOST_UPLOAD_SCREENSHOT": jobpost_upload_screenshot,
    "JOBPOST_MARK_PORTAL": jobpost_mark_portal,
    "JOBPOST_COMPLETE": jobpost_complete,
    "FILE_UPLOAD_CV": file_upload_cv,
    "CANDIDATE_ADD": candidate_add,
    "CANDIDATE_BULK_ADD": candidate_bulk_add,
    "CANDIDATE_PII_SET": candidate_pii_set,
    "SHORTLIST_DECIDE": shortlist_decide,
    "HOLD_REVERT": hold_revert,
    "SHORTLIST_HOLD_REVERT": shortlist_hold_revert,
    "OWNER_CANDIDATES_LIST": owner_candidates_list,
    "OWNER_DECIDE": owner_decide,
    "HR_WALKIN_SCHEDULE": hr_walkin_schedule,
    "WALKIN_SCHEDULE": walkin_schedule,
    "PRECALL_LIST": precall_list,
    "PRECALL_UPDATE": precall_update,
    "AUTO_REJECT_NOTPICK": auto_reject_notpick,
    "AUTO_RESCHEDULE_NO_SHOW": auto_reschedule_no_show,
    "PREINTERVIEW_STATUS": preinterview_status,
    "PREINTERVIEW_MARKS_SAVE": preinterview_marks_save,
    "TEST_LINK_CREATE": test_link_create,
    "TEST_TOKEN_VALIDATE": test_token_validate,
    "TEST_QUESTIONS_GET": test_questions_get,
    "TEST_SUBMIT_PUBLIC": test_submit_public,
    "TEST_RESULT_GET": test_result_get,
    "INPERSON_PIPELINE_LIST": inperson_pipeline_list,
    "INPERSON_MARKS_SAVE": inperson_marks_save,
    "TECH_SELECT": tech_select,
    "AUTO_REJECT_INPERSON_LOW": auto_reject_inperson_low,
    "TECH_PENDING_LIST": tech_pending_list,
    "EA_TECH_MARKS_SUBMIT": ea_tech_marks_submit,
    "ADMIN_EXCEL_MARKS_SUBMIT": admin_excel_marks_submit,
    "PASSFAIL_EVALUATE": passfail_evaluate,
    "TEST_FAIL_DECIDE": test_fail_decide,
    "FINAL_INTERVIEW_LIST": final_interview_list,
    "FINAL_SEND_OWNER": final_send_owner,
    "OWNER_FINAL_DECIDE": owner_final_decide,
    "HR_FINAL_HOLD_LIST": hr_final_hold_list,
    "HR_HOLD_SCHEDULE": hr_hold_schedule,
    "AUTO_REJECT_FINAL_NOSHOW": auto_reject_final_noshow,
    "JOINING_LIST": joining_list,
    "JOINING_SET_DATE": joining_set_date,
    "DOCS_UPLOAD": docs_upload,
    "DOCS_COMPLETE": docs_complete,
    "MARK_JOIN": mark_join,
    "PROBATION_LIST": probation_list,
    "PROBATION_SET": probation_set,
    "PROBATION_DECIDE": probation_decide,
    "PROBATION_COMPLETE": probation_complete,
    "ROLE_CHANGE": role_change,
    "EMPLOYEE_CREATE_FROM_CANDIDATE": employee_create_from_candidate,
    "EMPLOYEE_GET": employee_get,
    "TRAINING_MASTER_LIST": training_master_list,
    "TRAINING_MASTER_UPSERT": training_master_upsert,
    "TRAINING_ASSIGN": training_assign,
    "TRAINING_LIST": training_list,
    "TRAINING_STATUS_UPDATE": training_status_update,
    "TRAINING_SUMMARY": training_summary,
    "TRAINING_DASHBOARD": training_dashboard,
    "TRAINING_MARK_COMPLETE": training_mark_complete,
    "TRAINING_CLOSE": training_close,
    "TEST_MASTER_GET": test_master_get,
    "TEST_MASTER_UPSERT": test_master_upsert,
    "CANDIDATE_REQUIRED_TESTS_SET": candidate_required_tests_set,
    "CANDIDATE_TESTS_GET": candidate_tests_get,
    "CANDIDATE_TEST_SUBMIT": candidate_test_submit,
    "CANDIDATE_TEST_REVIEW": candidate_test_review,
    "CANDIDATE_TEST_ASSIGN": candidate_test_assign,
    "TESTS_QUEUE_LIST": tests_queue_list,
    "FAIL_CANDIDATES_LIST": fail_candidates_list,
    "SLA_CONFIG_GET": sla_config_get,
    "SLA_CONFIG_UPSERT": sla_config_upsert,
    "STEP_METRICS_QUERY": step_metrics_query,
    "REQUIREMENT_AUTO_CLOSE": requirement_auto_close,
    "REJECTION_LOG_LIST": rejection_log_list,
    "REJECT_REVERT": reject_revert,
    "HOLD_EXPIRY_CRON": hold_expiry_cron,
}


def dispatch(action: str, data: dict[str, Any], auth: AuthContext | None, db, cfg):
    action_u = str(action or "").upper().strip()
    handler = ACTION_HANDLERS.get(action_u)
    if not handler:
        raise ApiError("BAD_REQUEST", f"Unhandled action: {action_u}")
    if data is None:
        data = {}
    if not isinstance(data, dict):
        raise ApiError("BAD_REQUEST", "data must be an object")
    return handler(data, auth, db, cfg)
